server:
  port: 8086
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: TopAlumno-service
          uri: lb://TopAlumno
          predicates:
            - Path=/alumno/**
        - id: Pagos-service
          uri: lb://Pagos
          predicates:
            - Path=/pagos/**
        - id: Examen-service
          uri: lb://Examen
          predicates:
            - Path=/examen/**
